### ISSUE TITLE
Patient Record NULL Values

### ISSUE THREAD

**Issue by NilsG-S** [NilsG-S/team-null-back-end#24]
When getting records from the database I have found that the NULL values for weight, height, and blood pressure cause problems for input fields. Would it be better for me to handle these on the front-end, or have the back-end deal with them? I imagine there are reasons why the values are NULL in the database, so I wanted to clear it with you all before proceeding.

**Comment by IntJRG** [comment]
I think the reason we have those fields as NULLable is because a Patient Record is created as soon as an Appointment is created (this is because of the specification from Dr. Shin if I remember right), but those measurements aren't actually taken and inputted until the day the patient shows up for the appointment.

**Comment by NilsG-S** [comment]
@IntJRG Is there any reason we couldn't just make them zero? That would just as clearly indicate that no measurement had been taken.

**Comment by IntJRG** [comment]
Oh, I see what you're saying. Yeah, I don't see why they couldn't be zero.

**Comment by dlowrey** [comment]
@NilsG-S I will make them default 0 in this next PR.
